[package]
name = "currust"
version = "0.1.0"
edition = "2024"
description = "A tool to convert Windows cursors to Linux"
authors = ["hachispin"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
ico = "0.5.0"
x11rb = { version = "0.13.2", features = ["cursor"] }
