[package]
name = "currust"
version = "0.1.0"
edition = "2024"
description = "A tool to convert Windows cursors to Linux"
authors = ["hachispin"]

[dependencies]
anyhow = "1.0.100"
binrw = "0.15.0"
clap = { version = "4.5.53", features = ["derive"] }
dialoguer = "0.12.0"
ico = "0.5.0"
libc = "0.2.178"
rayon = "1.11.0"
