[package]
name = "currust"
version = "0.1.0"
edition = "2024"
description = "A tool to convert Windows cursors to Linux"
authors = ["hachispin"]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
ico = "0.5.0"
libc = "0.2.178"
x11 = { version = "2.21.0", features = ["xcursor"] }
